### ISSUE TITLE
Lack of necessary "requirements.txt".

### ISSUE THREAD

**Issue by d-serafly** [AI-Application-and-Integration-Lab/RDPN6D#1]
First of all, I want to express my appreciation for your outstanding work and the open-source spirit behind your project on GitHub. However, I encountered some difficulties while attempting to reproduce the project due to the absence of necessary installation files, "requirements.txt". It would be greatly helpful if you could provide the required requirements file.
Once again, thank you for your remarkable contribution to the open-source community. I look forward to hearing from you and potentially resolving this matter.

**Comment by d-serafly** [comment]
In addition, when executing the script "sh scripts/install_deps. sh", there is also a command "pip install-r requirements. txt". Is it the same file?

**Comment by p458732** [comment]
Hi,
I have updated the "requirements.txt" file.
