### ISSUE TITLE
lmo  test dataset

### ISSUE THREAD

**Issue by Luckyangle1232** [AI-Application-and-Integration-Lab/RDPN6D#3]
First of all, I want to express my appreciation for your outstanding work and the open-source spirit behind your project on GitHub. However, when I download only the lmo test dataset and ape.pth, using the command “. /core/gdrn_modeling/test_gdrn.sh configs/gdrn/lmo/a6_cPnP_AugAAETrunc_BG0.5_lmo_real_pbr0.1_40e.py 0 ape.pth”, it gives me an error.

FileNotFoundError: [Errno 2] No such file or directory: '/media/zhujq/deepl/6Dpose/RDPN6D-main/ datasets/ BOP_DATASETS/ lm/ image_set/ape_train.txt'

I would like to know how to use lmo's pre-trained models to test the accuracy of the model. Also, I would like to know how to train this model using train_pbr from lmo dataset.

**Comment by Luckyangle1232** [comment]
![Uploading 5913f243-6523-44b8-a8ab-d21b7aa31a41.png…]()

**Comment by p458732** [comment]
Hi,
Thank you for your interest in our work!
Have you also set up the metadata file according to the folder structure we provided?

**Comment by Luckyangle1232** [comment]
> Hi, Thank you for your interest in our work! Have you also set up the metadata file according to the folder structure we provided?

I only downloaded the metadata of lmo and arranged it according to your dataset. But when I run test. sh, the program still needs to read the lm's data from the header file.
Traceback (most recent call last):
  File "/media/zhujq/deepl/6Dpose/RDPN6D-main/core/gdrn_modeling/main_gdrn.py", line 29, in <module>
    from core.gdrn_modeling.dataset_factory import register_datasets_in_cfg
  File "/media/zhujq/deepl/6Dpose/RDPN6D-main/core/gdrn_modeling/../../core/gdrn_modeling/dataset_factory.py", line 8, in <module>
    from .datasets import lm_syn_imgn, lm_dataset_d2, lm_pbr, lm_blender, ycbv_pbr, ycbv_d2, ycbv_bop_test, delta_train, mp6d
  File "/media/zhujq/deepl/6Dpose/RDPN6D-main/core/gdrn_modeling/../../core/gdrn_modeling/datasets/lm_dataset_d2.py", line 547, in <module>
    with open(cur_ann_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/media/zhujq/deepl/6Dpose/RDPN6D-main/datasets/BOP_DATASETS/lm/image_set/ape_train.txt'

**Comment by Luckyangle1232** [comment]
![d7a46f69-fddb-4ede-9aab-1e131051feeb](https://github.com/user-attachments/assets/bcdf9de2-d55d-4942-a2fa-a4800acded95)
![e969939a-5989-4ed1-8f61-6757c35f4da1](https://github.com/user-attachments/assets/54421360-b9dc-4436-910a-ea6fc2eb4e21)
![Uploading d7a46f69-fddb-4ede-9aab-1e131051feeb.png…]()

**Comment by Luckyangle1232** [comment]
Hi, I would like to ask if I download the lm dataset, how can I use your image fusion tool, to generate new data.

**Comment by p458732** [comment]
Hi,
Could you also help set up the LM images and LM metadata files?  This is important because the original experimental setup trains on LM data and tests on LMO data.

For the image fusion tool, we currently use a "copy and paste" approach following the GDR-Net settings to generate synthetic images. I recommend exploring more advanced tools like BlenderProc4BOP [1] for potentially better results.

[1]: https://github.com/DLR-RM/BlenderProc/blob/main/README_BlenderProc4BOP.md#blenderproc4bop

**Comment by Luckyangle1232** [comment]
> Hi, Could you also help set up the LM images and LM metadata files? This is important because the original experimental setup trains on LM data and tests on LMO data.
> 
> For the image fusion tool, we currently use a "copy and paste" approach following the GDR-Net settings to generate synthetic images. I recommend exploring more advanced tools like BlenderProc4BOP [1](https://github.com/DLR-RM/BlenderProc/blob/main/README_BlenderProc4BOP.md#blenderproc4bop) for potentially better results.

If just testing pre-trained models on lmo dataset, do we need lm dataset as well?

**Comment by p458732** [comment]
Well, I think it is the most convenient way to test lmo, or you may need to modify the code to do it.

**Comment by Luckyangle1232** [comment]
> Well, I think it is the most convenient way to test lmo, or you may need to modify the code to do it.

If I follow your dataset to the full download, do I still need to use tool's tools for rendering and generating the relevant files?

**Comment by Luckyangle1232** [comment]
`[0725_210407@core/gdrn_modeling/engine.py:193] DBG images_per_batch:  24
[0725_210407@core/gdrn_modeling/engine.py:194] DBG dataset length:  15375
[0725_210407@core/gdrn_modeling/engine.py:195] DBG iters per epoch:  640
[0725_210407@core/gdrn_modeling/engine.py:196] DBG total iters:  102400
[ WARN:0@5.406] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('../data/lm_imgn/imgn/eggbox/000567_7-color.png'): can't open/read file: check file path/integrity
[ WARN:0@5.406] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('../data/lm_imgn/imgn/cat/001034_2-color.png'): can't open/read file: check file path/integrity
[ WARN:0@5.407] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('../data/lm_imgn/imgn/phone/000542_9-color.png'): can't open/read file: check file path/integrity
[ WARN:0@5.407] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('../data/BOP_DATASETS/lm/test/000006/rgb/001047.png'): can't open/read file: check file path/integrity
[ WARN:0@5.407] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('../data/lm_imgn/imgn/phone/000284_5-color.png'): can't open/read file: check file path/integrity
[ WARN:0@5.407] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('../data/lm_imgn/imgn/holepuncher/000248_9-color.png'): can't open/read file: check file path/integrity
[ WARN:0@5.409] global /io/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('../data/lm_imgn/imgn/holepuncher/000888_0-color.png'): can't open/read file: check file path/integrity`
When reading the dataset, it happens that the photos in the folder cannot be read。

**Comment by Luckyangle1232** [comment]
But when I use cv2.imread to read these images, the images work  fine.
