### ISSUE TITLE
KNN-NanoFLANN 

### ISSUE THREAD

**Issue by jhqwdk** [AI-Application-and-Integration-Lab/RDPN6D#4]
pip seems do not have the package "KNN-NanoFLANN", where can I find it？
![143568dfb53d69597f24965f1c45f738](https://github.com/user-attachments/assets/b2258f09-edf8-4cd1-8e99-d27c0c0b174e)

**Comment by willieChen58** [comment]
> pip seems do not have the package "KNN-NanoFLANN", where can I find it？ ![143568dfb53d69597f24965f1c45f738](https://private-user-images.githubusercontent.com/126046784/353659461-b2258f09-edf8-4cd1-8e99-d27c0c0b174e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NjA5MTksIm5iZiI6MTcyMjc2MDYxOSwicGF0aCI6Ii8xMjYwNDY3ODQvMzUzNjU5NDYxLWIyMjU4ZjA5LWVkZjgtNGNkMS04ZTk5LWQyN2MwYzBiMTc0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNFQwODM2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWRmZjJmNTRmNmZiMmM0NWMzNzgxNThhNTI1ODllZjhlYTQwN2EyM2U1YmI2OTE4ZTIzMmNlMjgxMTkzOWE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ta24ug29uvSPN-LS5BCjXYgQrtsy-1xho5e6O4UBmEA)

Hi, did you solve it?

**Comment by jhqwdk** [comment]
> > pip seems do not have the package "KNN-NanoFLANN", where can I find it？ ![143568dfb53d69597f24965f1c45f738](https://private-user-images.githubusercontent.com/126046784/353659461-b2258f09-edf8-4cd1-8e99-d27c0c0b174e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NjA5MTksIm5iZiI6MTcyMjc2MDYxOSwicGF0aCI6Ii8xMjYwNDY3ODQvMzUzNjU5NDYxLWIyMjU4ZjA5LWVkZjgtNGNkMS04ZTk5LWQyN2MwYzBiMTc0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNFQwODM2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWRmZjJmNTRmNmZiMmM0NWMzNzgxNThhNTI1ODllZjhlYTQwN2EyM2U1YmI2OTE4ZTIzMmNlMjgxMTkzOWE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ta24ug29uvSPN-LS5BCjXYgQrtsy-1xho5e6O4UBmEA)
> 
> Hi, did you solve it?

I solved this problem by installing an alternative library：flann

**Comment by willieChen58** [comment]
> > > pip seems do not have the package "KNN-NanoFLANN", where can I find it？ ![143568dfb53d69597f24965f1c45f738](https://private-user-images.githubusercontent.com/126046784/353659461-b2258f09-edf8-4cd1-8e99-d27c0c0b174e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NjA5MTksIm5iZiI6MTcyMjc2MDYxOSwicGF0aCI6Ii8xMjYwNDY3ODQvMzUzNjU5NDYxLWIyMjU4ZjA5LWVkZjgtNGNkMS04ZTk5LWQyN2MwYzBiMTc0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNFQwODM2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWRmZjJmNTRmNmZiMmM0NWMzNzgxNThhNTI1ODllZjhlYTQwN2EyM2U1YmI2OTE4ZTIzMmNlMjgxMTkzOWE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ta24ug29uvSPN-LS5BCjXYgQrtsy-1xho5e6O4UBmEA)
> > 
> > 
> > Hi, did you solve it?
> 
> I solved this problem by installing an alternative library：flann

Thanks! And i found it's ok to run the code without this library.
