### ISSUE TITLE
Can we train our own custom datasets？

### ISSUE THREAD

**Issue by willieChen58** [AI-Application-and-Integration-Lab/RDPN6D#5]
Hi, thanks for your outstanding work !! And I want to know that if it's possible to train on our custom datasets?

**Comment by p458732** [comment]
Hi,
Yes, you can train your custom datasets. However, pre-processing is necessary for model training. Here are the steps you may need to follow to generate your synthetic data:

1. Convert your objects to mesh files or point cloud files.
2. We recommend using BlenderProc4BOP to synthesize the training images (including depth and masks), or you can annotate your own dataset for object poses.
3. After completing steps 1 and 2, generate the xyz_crop for model training.

**Comment by willieChen58** [comment]
Thanks for your reply!!
I already have my custom datasets, including real and &nbsp;synthetic data. And I wonder how is the xyz_crop generated, maybe I should use the function in GDRNet? Moreover, could you tell me how&nbsp;should I put my data into a dataset folder for training? For example, just like the folder structure of LineMOD dataset.

发自我的iPhone


------------------ Original ------------------
From: Cancan ***@***.***&gt;
Date: Thu,Aug 1,2024 11:01 PM
To: AI-Application-and-Integration-Lab/RDPN6D ***@***.***&gt;
Cc: willieChen58 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [AI-Application-and-Integration-Lab/RDPN6D] Can we train our own custom datasets？ (Issue #5)





 
Hi,
 Yes, you can train your custom datasets. However, pre-processing is necessary for model training. Here are the steps you may need to follow to generate your synthetic data:
  
Convert your objects to mesh files or point cloud files. 

We recommend using BlenderProc4BOP to synthesize the training images (including depth and masks), or you can annotate your own dataset for object poses. 

After completing steps 1 and 2, generate the xyz_crop for model training.

**Comment by willieChen58** [comment]
> Hi, thanks for your outstanding work !! And I want to know that if it's possible to train on our custom datas

> Thanks for your reply!! I already have my custom datasets, including real and &nbsp;synthetic data. And I wonder how is the xyz_crop generated, maybe I should use the function in GDRNet? Moreover, could you tell me how&nbsp;should I put my data into a dataset folder for training? For example, just like the folder structure of LineMOD dataset.

**Comment by willieChen58** [comment]
> Hi, Yes, you can train your custom datasets. However, pre-processing is necessary for model training. Here are the steps you may need to follow to generate your synthetic data:
> 
> 1. Convert your objects to mesh files or point cloud files.
> 2. We recommend using BlenderProc4BOP to synthesize the training images (including depth and masks), or you can annotate your own dataset for object poses.
> 3. After completing steps 1 and 2, generate the xyz_crop for model training.
Thanks for your reply!! I already have my custom datasets, including real and  synthetic data. And I wonder how is the xyz_crop generated, maybe I should use the function in GDRNet? Moreover, could you tell me how should I put my data into a dataset folder for training? For example, just like the folder structure of LineMOD dataset.

**Comment by willieChen58** [comment]
> Hi, Yes, you can train your custom datasets. However, pre-processing is necessary for model training. Here are the steps you may need to follow to generate your synthetic data:
> 
> 1. Convert your objects to mesh files or point cloud files.
> 2. We recommend using BlenderProc4BOP to synthesize the training images (including depth and masks), or you can annotate your own dataset for object poses.
> 3. After completing steps 1 and 2, generate the xyz_crop for model training.

Thanks for your reply!! I already have my custom datasets, including real and  synthetic data. And I wonder how is the xyz_crop generated, maybe I should use the function in GDRNet? Moreover, could you tell me how should I put my data into a dataset folder for training? For example, just like the folder structure of LineMOD dataset.

**Comment by p458732** [comment]
Hi,
To generate xyz_crop files, you can refer to "tools/lmo/lmo_pbr_1_gen_xyz_crop.py" for guidance. Ensure that your dataset structure follows the same format as the other dataset folders.

However, you will need to create your own dataset configurations. This includes writing new files under "ref/" and "core/gdrn_modeling/datasets".

**Comment by willieChen58** [comment]
> Hi, To generate xyz_crop files, you can refer to "tools/lmo/lmo_pbr_1_gen_xyz_crop.py" for guidance. Ensure that your dataset structure follows the same format as the other dataset folders.
> 
> However, you will need to create your own dataset configurations. This includes writing new files under "ref/" and "core/gdrn_modeling/datasets".

Hi, i have succeeded in training on my data, but the loss_region : 2.3231e+02 (2.3300e+02) appears to be 2 orders of magnitude bigger than all the other losses during the training process. If it's not normal what reason has to do with this? And I wonder whether there is any way to improve it? Looking forward to your reply! Thanks a lot！
![1723110831787](https://github.com/user-attachments/assets/a8b0569c-f1a2-43fa-a9cf-611fd8905d10)

**Comment by willieChen58** [comment]
![image](https://github.com/user-attachments/assets/a6c2ec59-5e8a-4e5d-b93b-922ced16b622)
When I finished training, the value of loss_region remained at 2.2733e+02. Could you tell me how the loss_region was calculated? Or in which python file I can find it.

**Comment by willieChen58** [comment]
Well, in the end, i have succeeded in training on custom data by myself. And the test result is normal.
![image](https://github.com/user-attachments/assets/d3dcb084-da01-4fb1-8eab-8cdbe3a456be)

**Comment by jhqwdk** [comment]
> Well, in the end, i have succeeded in training on custom data by myself. And the test result is normal. ![image](https://private-user-images.githubusercontent.com/128902725/358439645-d3dcb084-da01-4fb1-8eab-8cdbe3a456be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NzgwMTAsIm5iZiI6MTcyNTc3NzcxMCwicGF0aCI6Ii8xMjg5MDI3MjUvMzU4NDM5NjQ1LWQzZGNiMDg0LWRhMDEtNGZiMS04ZWFiLThjZGJlM2E0NTZiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwNjQxNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDg5YzRmN2U3YjdlYzEyOGZlMzdhNGZmNDMwYmI0ZjVjN2M2OTY1OGQyNmNkNmNjNjZiZjA3MDhlYWVlNjFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M5edlZsNRXVOb2aZIJKfACYAefF0mgx1T6tjPmnugjg)

Hi, did you encounter the problem when test mp6d:
![92a686fdbb3522b18bafa257d7b7088b](https://github.com/user-attachments/assets/8eb2432c-d516-4946-8d2a-ad188ac2249f)
